{"uid":"b40171f0b53cc7ea","name":"Login to TMS-CaseManager and view all alerts in Common Queue1","fullName":"View Alerts in Common Queue: Login to TMS-CaseManager and view all alerts in Common Queue1","historyId":"5f0a781f665c67260d1a950a34b9a4c4","time":{"start":1756192815214,"stop":1756192816204,"duration":990},"description":"Tags: []","descriptionHtml":"<p>Tags: []</p>\n","status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='atoms-api-devv.solyticspartners.com', port=443): Max retries exceeded with url: /api/v1/qa/atoms/case-manager/filters/data/?page=1&page_size=5 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000188BA522D50>: Failed to resolve 'atoms-api-devv.solyticspartners.com' ([Errno 11001] getaddrinfo failed)\"))\n","statusTrace":"  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"TMS-CaseManager\\features\\steps\\case_steps.py\", line 29, in step_impl2\n    context.response = context.api.TestApi(\"POST\", context.token, endpoint, payload=payload)\n                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\OneDrive\\TMS-CaseManager API\\TMS-CaseManager\\utils\\common\\api_helper.py\", line 46, in TestApi\n    return requests.post(\n           ~~~~~~~~~~~~~^\n        self.URL + endPoint,\n        ^^^^^^^^^^^^^^^^^^^^\n        headers=headers,\n        ^^^^^^^^^^^^^^^^\n        json=payload,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"Tags: []","status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='atoms-api-devv.solyticspartners.com', port=443): Max retries exceeded with url: /api/v1/qa/atoms/case-manager/filters/data/?page=1&page_size=5 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000188BA522D50>: Failed to resolve 'atoms-api-devv.solyticspartners.com' ([Errno 11001] getaddrinfo failed)\"))\n","statusTrace":"  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"TMS-CaseManager\\features\\steps\\case_steps.py\", line 29, in step_impl2\n    context.response = context.api.TestApi(\"POST\", context.token, endpoint, payload=payload)\n                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\OneDrive\\TMS-CaseManager API\\TMS-CaseManager\\utils\\common\\api_helper.py\", line 46, in TestApi\n    return requests.post(\n           ~~~~~~~~~~~~~^\n        self.URL + endPoint,\n        ^^^^^^^^^^^^^^^^^^^^\n        headers=headers,\n        ^^^^^^^^^^^^^^^^\n        json=payload,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[{"name":"Given the user is logged in to TMS-CaseManager","time":{"start":1756192815215,"stop":1756192816189,"duration":974},"status":"passed","steps":[{"name":"the user is logged in to TMS-CaseManager","time":{"start":1756192815215,"stop":1756192816189,"duration":974},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false}],"attachments":[],"parameters":[],"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":1,"attachmentStep":false},{"name":"When the user navigates to the Common Queue","time":{"start":1756192816189,"stop":1756192816198,"duration":9},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='atoms-api-devv.solyticspartners.com', port=443): Max retries exceeded with url: /api/v1/qa/atoms/case-manager/filters/data/?page=1&page_size=5 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000188BA522D50>: Failed to resolve 'atoms-api-devv.solyticspartners.com' ([Errno 11001] getaddrinfo failed)\"))\n","statusTrace":"  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"TMS-CaseManager\\features\\steps\\case_steps.py\", line 29, in step_impl2\n    context.response = context.api.TestApi(\"POST\", context.token, endpoint, payload=payload)\n                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\OneDrive\\TMS-CaseManager API\\TMS-CaseManager\\utils\\common\\api_helper.py\", line 46, in TestApi\n    return requests.post(\n           ~~~~~~~~~~~~~^\n        self.URL + endPoint,\n        ^^^^^^^^^^^^^^^^^^^^\n        headers=headers,\n        ^^^^^^^^^^^^^^^^\n        json=payload,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[{"name":"the user navigates to the Common Queue","time":{"start":1756192816189,"stop":1756192816195,"duration":6},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='atoms-api-devv.solyticspartners.com', port=443): Max retries exceeded with url: /api/v1/qa/atoms/case-manager/filters/data/?page=1&page_size=5 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000188BA522D50>: Failed to resolve 'atoms-api-devv.solyticspartners.com' ([Errno 11001] getaddrinfo failed)\"))\n","statusTrace":"  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"TMS-CaseManager\\features\\steps\\case_steps.py\", line 29, in step_impl2\n    context.response = context.api.TestApi(\"POST\", context.token, endpoint, payload=payload)\n                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\OneDrive\\TMS-CaseManager API\\TMS-CaseManager\\utils\\common\\api_helper.py\", line 46, in TestApi\n    return requests.post(\n           ~~~~~~~~~~~~~^\n        self.URL + endPoint,\n        ^^^^^^^^^^^^^^^^^^^^\n        headers=headers,\n        ^^^^^^^^^^^^^^^^\n        json=payload,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\SHRINIDHI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[{"uid":"741b0bd448b3c3b","name":"Error in step: the user navigates to the Common Queue","source":"741b0bd448b3c3b.txt","type":"text/plain","size":368}],"parameters":[],"hasContent":true,"attachmentsCount":1,"shouldDisplayMessage":true,"stepsCount":0,"attachmentStep":false}],"attachments":[],"parameters":[],"hasContent":true,"attachmentsCount":1,"shouldDisplayMessage":false,"stepsCount":1,"attachmentStep":false},{"name":"Then the system should display all alerts with Alert ID and Transaction Type","time":{"start":1756192816204,"stop":1756192816204,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false},{"name":"Then Investigate one of the case","time":{"start":1756192816204,"stop":1756192816204,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"attachmentStep":false}],"attachments":[{"uid":"bb02e42d0819d0ee","name":"Failure in step: the user navigates to the Common Queue","source":"bb02e42d0819d0ee.txt","type":"text/plain","size":413}],"parameters":[],"hasContent":true,"attachmentsCount":2,"shouldDisplayMessage":false,"stepsCount":6,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"View Alerts in Common Queue"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"b40171f0b53cc7ea.json","parameterValues":[]}